// Real compiled UI / trusted input. No state, score, orientation callback or completion setters.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path');
const analysisSuite=['coach-analysis','bell-repair'].includes(process.env.BOXER_WAVE_EVIDENCE);
const dir=path.resolve(__dirname,'../evidence/wave1/'+(process.env.BOXER_WAVE_EVIDENCE==='bell-repair'?'bell-repair':analysisSuite?'coach-analysis':'coach-ui')+'/coach-browser');fs.mkdirSync(dir,{recursive:true});
const report={scope:'COMPILED_COACH_UI_SYNTHETIC_MOBILE_VIEWPORT_NOT_PHONE_UAT',checks:[],errors:[],states:{},mediaRequests:[]};
function check(ok,label){report.checks.push({name:label,pass:!!ok});if(!ok)throw Error(label);}
function frozen(s){return !s.gameplayInput&&!s.playerEnabled&&!s.opponentEnabled&&s.seconds===0&&s.playerHP===100&&s.opponentHP===100&&s.playerStamina===100&&s.opponentStamina===100&&s.playerCapacity===100&&s.opponentCapacity===100;}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--use-angle=d3d11','--disable-background-timer-throttling','--disable-renderer-backgrounding']});let page;
try{
 const ctx=await browser.newContext({viewport:{width:540,height:960},hasTouch:true});page=await ctx.newPage();const touch=await ctx.newCDPSession(page),pending=new Set();let action='initial-load';const started=Date.now();
 for(const type of ['request','requestfinished','requestfailed'])page.on(type,r=>{if(r.url().includes('/StreamingAssets/')){const entry={type,action,at:Date.now()-started,url:r.url(),range:r.headers().range,error:r.failure()?.errorText};report.mediaRequests.push(entry);if(type==='requestfailed')console.log('MEDIA_REQUEST_FAILED',JSON.stringify(entry));}});
 page.on('request',r=>{if(r.url().includes('/Build/')||r.url().includes('/StreamingAssets/'))pending.add(r);});page.on('requestfinished',r=>pending.delete(r));
 page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});page.on('requestfailed',r=>{pending.delete(r);report.errors.push(r.url()+' '+r.failure()?.errorText);});page.on('response',r=>{if(r.status()>=400)report.errors.push('HTTP '+r.status()+' '+r.url());});
 report.url=process.argv[2]||'http://127.0.0.1:8000/?desktop=1&metrics=1';await page.goto(report.url);report.productVersion=await page.evaluate(()=>productVersion);await page.locator('#enable').click();
 const snap=()=>page.evaluate(()=>window.boxerWave1Snapshot);
 async function state(label,screen){action=label;await page.waitForFunction(s=>window.boxerWave1Snapshot?.screen===s,screen,{timeout:150000});await page.waitForTimeout(100);const s=await snap();report.states[label]=s;await page.screenshot({path:path.join(dir,label+'.png')});return s;}
 async function tap(x,y){const v=page.viewportSize(),scale=Math.min(v.width/540,v.height/960),ox=(v.width-540*scale)/2,oy=(v.height-960*scale)/2;
  await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:ox+x*scale,y:oy+y*scale}]});await page.waitForTimeout(75);await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(150);}
 const coachEntryY=analysisSuite?763:853,trainY=analysisSuite?808:828,coachHomeY=analysisSuite?893:913;
 async function choose(module){await tap(390,analysisSuite?274+90*module:289+96*module);await page.waitForFunction(m=>window.boxerWave1Snapshot.coachModule===m,['Head','Footwork','Punches','Guard','Conditioning'][module]);}
 async function practice(module,stage){await choose(module);await tap(270,trainY);const s=await state('practice-'+stage,'Onboarding');check(s.trainingStage===stage&&s.trainingFromCoach&&!s.opponentEnabled&&s.seconds===0&&s.opponentAttacks===0,'Coach starts selected unscored '+stage);return s;}
 async function punch(dx=0,dy=0){await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:2,x:420,y:710}]});await page.waitForTimeout(85);if(dx||dy)await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:2,x:420+dx,y:710+dy}]});await page.waitForTimeout(85);await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(800);}
 await state('home','Home');
 if(analysisSuite){await tap(270,853);await page.waitForTimeout(200);check((await snap()).screen==='Home'&&frozen(await snap()),'retired duplicate training entry does not open another route');}
 await tap(270,coachEntryY);let s=await state('coach','Coach');check(frozen(s)&&s.coachArtLoaded&&s.coachCompletionMask===0,'Coach native hub includes art and no combat or false progress');
 if(analysisSuite){await tap(270,728);s=await state('review-empty','CoachReview');check(!s.hasMatchReview&&s.coachSuggestions.length===0&&frozen(s),'fresh install has honest empty review with no fake statistics');await page.keyboard.press('k');await page.waitForTimeout(250);check(!(await snap()).hasMatchReview&&frozen(await snap()),'empty review blocks punches and cannot fabricate record');await tap(270,893);await state('review-empty-back','Coach');}
 await page.keyboard.press('k');await page.keyboard.press('w');await page.waitForTimeout(250);check(frozen(await snap()),'Coach keys cannot move, punch or spend');
 for(const [module,name] of [[3,'guard'],[4,'conditioning']]){await choose(module);await tap(270,trainY);s=await state(name+'-info','TrainingInfo');check(frozen(s)&&s.coachCompletionMask===0,'information '+name+' has no gameplay or stat award');check(s.coachInfoContentHeight>0&&s.coachInfoContentHeight<=320,'information '+name+' full native text fits its card');await page.keyboard.press('k');await page.waitForTimeout(250);check(frozen(await snap()),'information '+name+' rejects punch');await tap(270,873);await state(name+'-back','Coach');check((await snap()).coachModule===['Guard','Conditioning'][module-3],'back preserves selected '+name);}
 await choose(4);await tap(270,trainY);await state('info-to-practice','TrainingInfo');await tap(270,783);s=await state('linked-punches','Onboarding');check(s.trainingStage==='PUNCHES'&&s.trainingFromCoach&&!s.opponentEnabled&&s.acceptedPunches===0,'information links to real punch practice without menu punch');await tap(270,429);s=await state('cancelled','Coach');check(frozen(s)&&s.coachCompletionMask===0&&!s.tutorialSeen,'cancel does not mark any lesson complete');
 await practice(0,'HEADCONTROL');for(const key of ['q','e']){await page.keyboard.down(key);await page.waitForTimeout(500);await page.keyboard.up(key);await page.waitForTimeout(100);}await page.waitForFunction(()=>window.boxerWave1Snapshot.trainingReady);await tap(270,494);s=await state('head-completed','Coach');check(s.coachCompletionMask===1&&!s.tutorialSeen&&frozen(s),'head-only completion returns Coach without whole tutorial award');
 await practice(1,'FOOTWORK');for(const key of ['w','s','a','d']){await page.keyboard.down(key);await page.waitForTimeout(300);await page.keyboard.up(key);await page.waitForTimeout(100);}await page.waitForFunction(()=>window.boxerWave1Snapshot.trainingReady);await tap(270,354);s=await state('feet-completed','Coach');check(s.coachCompletionMask===3&&!s.tutorialSeen&&frozen(s),'footwork completion is separate and unscored');
 s=await practice(2,'PUNCHES');check(s.acceptedPunches===0&&!s.trainingReady,'new punch lesson has no inherited practice credit');for(const [dx,dy] of [[0,0],[0,0],[0,-105],[0,105],[-105,0],[85,0]])await punch(dx,dy);await page.waitForFunction(()=>window.boxerWave1Snapshot.trainingReady);s=await snap();check(s.acceptedPunches===6&&s.impactHits===0&&s.impactBlocks===0&&s.playerHP===100&&s.playerStamina===100&&s.playerCapacity===100&&s.seconds===0,'real gestures animate unscored practice without fake impact or resource changes');await tap(270,354);s=await state('all-completed','Coach');check(s.coachCompletionMask===7&&s.tutorialSeen&&frozen(s),'all three practiced lessons complete controls');
 if(analysisSuite)check(!(await snap()).hasMatchReview,'unscored completed lessons never create match analytics');
 await tap(270,coachHomeY);s=await state('coach-home','Home');check(frozen(s),'Coach Home returns locked clean Home');
 check(!report.mediaRequests.some(r=>r.type==='request'&&r.url.includes('ring-girl.mp4')),'Home/Coach/practice do not load unused ring video');
 // Exercise the ordinary intro/bout lifecycle before persistence reload.
 await tap(270,674);await state('completed-controls-preview','Preview');await tap(270,779);await state('completed-controls-fight','Fight');
 if(analysisSuite){await punch();await punch(0,-105);await punch(-105,0);}
 await page.waitForFunction(()=>window.boxerWave1Snapshot?.screen==='Result',null,{timeout:65000});
 let saved;
 if(analysisSuite){
  s=await state('first-match-result','Result');const r=s.lastMatchReview;saved=JSON.stringify(r);
  check(s.hasMatchReview&&r.schema===1&&r.sourceVersion===report.productVersion&&r.result===s.result&&r.reason===s.reason&&r.seconds===s.seconds,'actual completed bout captures versioned result and scored time');
  check(r.playerHP===s.playerHP&&r.opponentHP===s.opponentHP&&r.playerStamina===s.playerStamina&&r.playerCapacity===s.playerCapacity,'last-match endpoints equal exact authoritative HP and energy');
  check(r.accepted===s.acceptedPunches&&r.hits===s.playerHits&&r.blocked===s.opponentBlocks&&r.misses===s.playerMisses&&r.received===s.opponentHits&&r.defended===s.playerBlocks&&r.opponentMisses===s.opponentMisses,'stored counters distinguish shots hits blocked misses and opponent outcomes');
  check(r.accepted>=r.hits+r.blocked+r.misses&&r.accepted>0,'resolved denominator never counts unscored or unresolved shots');
  await tap(270,693);s=await state('result-review','CoachReview');check(frozen(s)&&JSON.stringify(s.lastMatchReview)===saved,'Result opens frozen analysis without destroying captured statistics');
  check(s.coachReviewContentHeight>0&&s.coachReviewContentHeight<=200,'all six native statistic lines fit review card');
  const mods=[];if(r.received>0)mods.push('Head');if(r.misses>0)mods.push('Footwork');mods.push('Punches');if(mods.length<3)mods.push('Conditioning');if(mods.length<3)mods.push('Guard');
  check(JSON.stringify(s.coachSuggestions)===JSON.stringify(mods),'suggestions derive only from actual counters and existing modules');
  await page.keyboard.press('k');await page.keyboard.press('w');await page.waitForTimeout(250);check(frozen(await snap())&&JSON.stringify((await snap()).lastMatchReview)===saved,'analysis rejects gameplay and preserves completed record');
  await page.setViewportSize({width:375,height:812});await page.waitForTimeout(600);s=await state('review-phone-375','CoachReview');check(frozen(s)&&s.coachReviewContentHeight<=200,'phone-size review redraw fits real endpoint text');
  await tap(270,594);s=await state('supplemental-first',mods[0]==='Conditioning'||mods[0]==='Guard'?'TrainingInfo':'Onboarding');
  check(s.coachModule===mods[0]&&JSON.stringify(s.lastMatchReview)===saved&&!s.opponentEnabled,'trusted phone tap routes to genuine suggested existing module without replacing record');
  check(s.acceptedPunches===0&&s.seconds===0&&s.playerHP===100&&s.playerStamina===100&&s.playerCapacity===100,'supplemental practice is fresh unscored and menu tap does not punch');
  await tap(270,s.trainingStage==='HEADCONTROL'?569:429);await state('supplemental-cancel-coach','Coach');check(JSON.stringify((await snap()).lastMatchReview)===saved,'cancel supplemental practice leaves match analysis unchanged');
  await page.setViewportSize({width:540,height:960});await page.waitForTimeout(500);await tap(270,coachHomeY);await state('supplemental-home','Home');
  await tap(270,674);await state('review-cancel-preview','Preview');await tap(270,779);await state('review-cancel-intro','Intro');await page.locator('#ring-back').click();s=await state('review-cancel-home','Home');check(JSON.stringify(s.lastMatchReview)===saved,'cancelled intro never replaces last completed match');
  await tap(270,674);await state('second-preview','Preview');await tap(270,779);s=await state('second-fight','Fight');check(JSON.stringify(s.lastMatchReview)===saved,'running next bout retains prior completed record');
  s=await state('second-result','Result');check(s.hasMatchReview&&s.lastMatchReview.id!==r.id&&s.lastMatchReview.seconds===s.seconds&&s.lastMatchReview.accepted===s.acceptedPunches&&s.lastMatchReview.playerHP===s.playerHP,'next completed bout replaces record once with its own actual statistics');saved=JSON.stringify(s.lastMatchReview);
 }
 await tap(270,869);s=await state('completed-controls-home','Home');check(s.coachCompletionMask===7&&s.tutorialSeen,'ordinary fight does not erase control completion');
 await page.waitForTimeout(700);for(let i=0;i<300&&pending.size;i++)await page.waitForTimeout(100);check(pending.size===0,'all Unity and media transfers complete before persistence reload');action='persistence-reload';await page.reload();await page.locator('#enable').click();s=await state('reload-home','Home');check(s.coachCompletionMask===7&&s.tutorialSeen,'genuine lesson completion persists reload');if(analysisSuite)check(s.hasMatchReview&&JSON.stringify(s.lastMatchReview)===saved,'latest completed match persists exact record across reload');await tap(270,coachEntryY);await state('reload-coach','Coach');
 await page.setViewportSize({width:375,height:812});await page.waitForTimeout(600);s=await state('coach-phone-375','Coach');check(frozen(s)&&s.coachArtLoaded,'phone-size portrait keeps native art/cards and locks');await choose(3);await tap(270,trainY);s=await state('guard-phone-375','TrainingInfo');check(frozen(s),'scaled trusted touch enters phone-size information');await tap(270,873);await state('coach-phone-back','Coach');
 await page.setViewportSize({width:960,height:540});await page.waitForTimeout(600);s=await state('coach-landscape','Coach');check(frozen(s),'landscape redraw stays locked');if(analysisSuite){await tap(270,728);s=await state('review-landscape','CoachReview');check(frozen(s)&&JSON.stringify(s.lastMatchReview)===saved&&s.coachReviewContentHeight<=200,'landscape review keeps exact persisted statistics and bounded text');await tap(270,893);await state('review-landscape-back','Coach');}await tap(270,coachHomeY);s=await state('landscape-home','Home');check(frozen(s),'landscape safe-area route Home works');
 check(s.players===1&&s.opponents===1,'Coach navigation creates no duplicate actors');check(report.errors.length===0,'Coach UI has zero JS/load/HTTP errors');report.status='PASS';
}catch(e){report.status='FAIL';report.failure=String(e);process.exitCode=1;if(page){try{report.failureState=await page.evaluate(()=>window.boxerWave1Snapshot);await page.screenshot({path:path.join(dir,'failure.png')});}catch{}}}finally{fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify(report,null,2));console.log(report.status,report.checks.length,report.failure||'');await browser.close();}})();
