// Real compiled UI / trusted input. No state, score, orientation callback or completion setters.
const {chromium}=require('playwright'),fs=require('fs'),path=require('path');
const dir=path.resolve(__dirname,'../evidence/wave1/coach-ui/coach-browser');fs.mkdirSync(dir,{recursive:true});
const report={scope:'COMPILED_COACH_UI_SYNTHETIC_MOBILE_VIEWPORT_NOT_PHONE_UAT',checks:[],errors:[],states:{},mediaRequests:[]};
function check(ok,label){report.checks.push({name:label,pass:!!ok});if(!ok)throw Error(label);}
function frozen(s){return !s.gameplayInput&&!s.playerEnabled&&!s.opponentEnabled&&s.seconds===0&&s.playerHP===100&&s.opponentHP===100&&s.playerStamina===100&&s.opponentStamina===100&&s.playerCapacity===100&&s.opponentCapacity===100;}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--use-angle=d3d11','--disable-background-timer-throttling','--disable-renderer-backgrounding']});let page;
try{
 const ctx=await browser.newContext({viewport:{width:540,height:960},hasTouch:true});page=await ctx.newPage();const touch=await ctx.newCDPSession(page),pending=new Set();let action='initial-load';const started=Date.now();
 for(const type of ['request','requestfinished','requestfailed'])page.on(type,r=>{if(r.url().includes('/StreamingAssets/')){const entry={type,action,at:Date.now()-started,url:r.url(),range:r.headers().range,error:r.failure()?.errorText};report.mediaRequests.push(entry);if(type==='requestfailed')console.log('MEDIA_REQUEST_FAILED',JSON.stringify(entry));}});
 page.on('request',r=>{if(r.url().includes('/Build/')||r.url().includes('/StreamingAssets/'))pending.add(r);});page.on('requestfinished',r=>pending.delete(r));
 page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});page.on('requestfailed',r=>{pending.delete(r);report.errors.push(r.url()+' '+r.failure()?.errorText);});page.on('response',r=>{if(r.status()>=400)report.errors.push('HTTP '+r.status()+' '+r.url());});
 report.url=process.argv[2]||'http://127.0.0.1:8000/?desktop=1&metrics=1';await page.goto(report.url);report.productVersion=await page.evaluate(()=>productVersion);await page.locator('#enable').click();
 const snap=()=>page.evaluate(()=>window.boxerWave1Snapshot);
 async function state(label,screen){action=label;await page.waitForFunction(s=>window.boxerWave1Snapshot?.screen===s,screen,{timeout:150000});await page.waitForTimeout(100);const s=await snap();report.states[label]=s;await page.screenshot({path:path.join(dir,label+'.png')});return s;}
 async function tap(x,y){const v=page.viewportSize(),scale=Math.min(v.width/540,v.height/960),ox=(v.width-540*scale)/2,oy=(v.height-960*scale)/2;
  await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:ox+x*scale,y:oy+y*scale}]});await page.waitForTimeout(75);await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(150);}
 async function choose(module){await tap(390,289+96*module);await page.waitForFunction(m=>window.boxerWave1Snapshot.coachModule===m,['Head','Footwork','Punches','Guard','Conditioning'][module]);}
 async function practice(module,stage){await choose(module);await tap(270,828);const s=await state('practice-'+stage,'Onboarding');check(s.trainingStage===stage&&s.trainingFromCoach&&!s.opponentEnabled&&s.seconds===0&&s.opponentAttacks===0,'Coach starts selected unscored '+stage);return s;}
 async function punch(dx=0,dy=0){await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:2,x:420,y:710}]});await page.waitForTimeout(85);if(dx||dy)await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:2,x:420+dx,y:710+dy}]});await page.waitForTimeout(85);await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(800);}
 await state('home','Home');await tap(270,853);let s=await state('coach','Coach');check(frozen(s)&&s.coachArtLoaded&&s.coachCompletionMask===0,'Coach native hub includes art and no combat or false progress');
 await page.keyboard.press('k');await page.keyboard.press('w');await page.waitForTimeout(250);check(frozen(await snap()),'Coach keys cannot move, punch or spend');
 for(const [module,name] of [[3,'guard'],[4,'conditioning']]){await choose(module);await tap(270,828);s=await state(name+'-info','TrainingInfo');check(frozen(s)&&s.coachCompletionMask===0,'information '+name+' has no gameplay or stat award');check(s.coachInfoContentHeight>0&&s.coachInfoContentHeight<=320,'information '+name+' full native text fits its card');await page.keyboard.press('k');await page.waitForTimeout(250);check(frozen(await snap()),'information '+name+' rejects punch');await tap(270,873);await state(name+'-back','Coach');check((await snap()).coachModule===['Guard','Conditioning'][module-3],'back preserves selected '+name);}
 await choose(4);await tap(270,828);await state('info-to-practice','TrainingInfo');await tap(270,783);s=await state('linked-punches','Onboarding');check(s.trainingStage==='PUNCHES'&&s.trainingFromCoach&&!s.opponentEnabled&&s.acceptedPunches===0,'information links to real punch practice without menu punch');await tap(270,429);s=await state('cancelled','Coach');check(frozen(s)&&s.coachCompletionMask===0&&!s.tutorialSeen,'cancel does not mark any lesson complete');
 await practice(0,'HEADCONTROL');for(const key of ['q','e']){await page.keyboard.down(key);await page.waitForTimeout(500);await page.keyboard.up(key);await page.waitForTimeout(100);}await page.waitForFunction(()=>window.boxerWave1Snapshot.trainingReady);await tap(270,494);s=await state('head-completed','Coach');check(s.coachCompletionMask===1&&!s.tutorialSeen&&frozen(s),'head-only completion returns Coach without whole tutorial award');
 await practice(1,'FOOTWORK');for(const key of ['w','s','a','d']){await page.keyboard.down(key);await page.waitForTimeout(300);await page.keyboard.up(key);await page.waitForTimeout(100);}await page.waitForFunction(()=>window.boxerWave1Snapshot.trainingReady);await tap(270,354);s=await state('feet-completed','Coach');check(s.coachCompletionMask===3&&!s.tutorialSeen&&frozen(s),'footwork completion is separate and unscored');
 s=await practice(2,'PUNCHES');check(s.acceptedPunches===0&&!s.trainingReady,'new punch lesson has no inherited practice credit');for(const [dx,dy] of [[0,0],[0,0],[0,-105],[0,105],[-105,0],[85,0]])await punch(dx,dy);await page.waitForFunction(()=>window.boxerWave1Snapshot.trainingReady);s=await snap();check(s.acceptedPunches===6&&s.impactHits===0&&s.impactBlocks===0&&s.playerHP===100&&s.playerStamina===100&&s.playerCapacity===100&&s.seconds===0,'real gestures animate unscored practice without fake impact or resource changes');await tap(270,354);s=await state('all-completed','Coach');check(s.coachCompletionMask===7&&s.tutorialSeen&&frozen(s),'all three practiced lessons complete controls');
 await tap(270,913);s=await state('coach-home','Home');check(frozen(s),'Coach Home returns locked clean Home');
 check(!report.mediaRequests.some(r=>r.type==='request'&&r.url.includes('ring-girl.mp4')),'Home/Coach/practice do not load unused ring video');
 // Exercise the ordinary intro/bout lifecycle before persistence reload.
 await tap(270,674);await state('completed-controls-preview','Preview');await tap(270,779);await state('completed-controls-fight','Fight');
 await page.waitForFunction(()=>window.boxerWave1Snapshot?.screen==='Result',null,{timeout:65000});await tap(270,869);s=await state('completed-controls-home','Home');check(s.coachCompletionMask===7&&s.tutorialSeen,'ordinary fight does not erase control completion');
 await page.waitForTimeout(700);for(let i=0;i<300&&pending.size;i++)await page.waitForTimeout(100);check(pending.size===0,'all Unity and media transfers complete before persistence reload');action='persistence-reload';await page.reload();await page.locator('#enable').click();s=await state('reload-home','Home');check(s.coachCompletionMask===7&&s.tutorialSeen,'genuine lesson completion persists reload');await tap(270,853);await state('reload-coach','Coach');
 await page.setViewportSize({width:375,height:812});await page.waitForTimeout(600);s=await state('coach-phone-375','Coach');check(frozen(s)&&s.coachArtLoaded,'phone-size portrait keeps native art/cards and locks');await choose(3);await tap(270,828);s=await state('guard-phone-375','TrainingInfo');check(frozen(s),'scaled trusted touch enters phone-size information');await tap(270,873);await state('coach-phone-back','Coach');
 await page.setViewportSize({width:960,height:540});await page.waitForTimeout(600);s=await state('coach-landscape','Coach');check(frozen(s),'landscape redraw stays locked');await tap(270,913);s=await state('landscape-home','Home');check(frozen(s),'landscape safe-area route Home works');
 check(s.players===1&&s.opponents===1,'Coach navigation creates no duplicate actors');check(report.errors.length===0,'Coach UI has zero JS/load/HTTP errors');report.status='PASS';
}catch(e){report.status='FAIL';report.failure=String(e);process.exitCode=1;if(page){try{report.failureState=await page.evaluate(()=>window.boxerWave1Snapshot);await page.screenshot({path:path.join(dir,'failure.png')});}catch{}}}finally{fs.writeFileSync(path.join(dir,'report.json'),JSON.stringify(report,null,2));console.log(report.status,report.checks.length,report.failure||'');await browser.close();}})();
